import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { Subscription } from 'rxjs';
import { firebaseAuth } from '../../firebase';
import { FirestoreQuickMatch } from '../quick-match.models';
import { QuickMatchService } from '../quick-match.service';

@Component({selector:'app-battle-history-page',standalone:true,imports:[CommonModule,RouterLink],template:`
<main><button class="back" (click)="router.navigate(['/multiplayer-battle'])">‹</button><section><p class="eye">Battle Records</p><h1>Battle History</h1><p class="error" *ngIf="error">{{error}}</p><p class="empty" *ngIf="!matches.length&&!error">No completed battles yet.</p><article *ngFor="let match of matches"><div><small>Quick Match</small><strong>{{opponent(match)}}</strong><span>{{result(match)}}</span></div><a [routerLink]="['/multiplayer/result',match.id]">View</a></article></section></main>`,styles:[`
:host{display:block;background:#07100f;color:#fff8df}main{min-height:100svh;background:linear-gradient(#07100faa,#07100fee),url('/multiplayer-page.png') center/cover fixed;padding:calc(env(safe-area-inset-top) + 4rem) 1rem calc(env(safe-area-inset-bottom) + 2rem)}section{max-width:38rem;margin:auto;border:2px solid #d8b15f;border-radius:12px;background:#0e1112e8;padding:1rem}.back{position:fixed;top:calc(env(safe-area-inset-top) + 1rem);left:1rem;width:44px;height:44px;border:2px solid #d8b15f;border-radius:50%;background:#111;color:#f8d36c;font-size:2rem}.eye,h1{text-align:center}.eye{color:#f5d36e;font-weight:900;text-transform:uppercase}h1{font:900 2.5rem Georgia}article{display:flex;align-items:center;gap:.7rem;margin:.7rem 0;padding:.9rem;border:2px solid #d8b15f;border-radius:9px;background:#20564e}article div{flex:1}article *{display:block}article small{color:#f5d36e;font-weight:900;text-transform:uppercase}article a{padding:.7rem;border:2px solid #ffe28a;border-radius:8px;background:#e8bb49;color:#201407;font-weight:900;text-decoration:none}.empty,.error{text-align:center;padding:1rem}`]})
export class BattleHistoryPage implements OnInit,OnDestroy{matches:FirestoreQuickMatch[]=[];error='';private sub?:Subscription;constructor(public router:Router,private service:QuickMatchService){}ngOnInit(){this.sub=this.service.observeMatchHistory().subscribe({next:x=>this.matches=x,error:()=>this.error='Could not load battle history.'})}ngOnDestroy(){this.sub?.unsubscribe()}opponent(m:FirestoreQuickMatch){const uid=firebaseAuth.currentUser?.uid;const id=m.playerIds.find(x=>x!==uid);return id?m.players[id]?.displayName||m.players[id]?.username||'Explorer':'Waiting match'}result(m:FirestoreQuickMatch){const uid=firebaseAuth.currentUser?.uid;if(m.completionReason==='forfeit')return m.winnerId===uid?'Victory — opponent forfeited':'Defeat — you forfeited';return m.winnerId===uid?'Victory':'Defeat'}}
